### ISSUE TITLE
Incompatible with scikit-learn 1.9: _get_n_samples_bootstrap / _generate_sample_indices signature change

### ISSUE THREAD

**Issue by jeongyoonlee** [scikit-learn-contrib/forest-confidence-interval#121]
**Describe the bug**

`calc_inbag()` calls scikit-learn's private `_get_n_samples_bootstrap` and `_generate_sample_indices` with their pre-1.9 signatures. scikit-learn 1.9 ([scikit-learn#31529](https://github.com/scikit-learn/scikit-learn/pull/31529)) made `sample_weight` a **required** positional argument on both, so any `random_forest_error(..., inbag=None)` call raises `TypeError` under scikit-learn >= 1.9. There is no version guard, so this affects 0.6, 0.7, and current `master`.

**To Reproduce**

forestci 0.7, scikit-learn 1.9.0:

```python
import numpy as np
from sklearn.ensemble import RandomForestRegressor
import forestci as fci

rng = np.random.RandomState(0)
X, y = rng.rand(100, 5), rng.rand(100)
rf = RandomForestRegressor(n_estimators=50, random_state=0).fit(X, y)
fci.random_forest_error(rf, X.shape, X)
```

```
File ".../forestci/forestci.py", line 73, in calc_inbag
    n_samples_bootstrap = _get_n_samples_bootstrap(n_samples, forest.max_samples)
TypeError: _get_n_samples_bootstrap() missing 1 required positional argument: 'sample_weight'
```

Once `_get_n_samples_bootstrap` is fixed, the very next call in `calc_inbag` fails the same way — `_generate_sample_indices(rs, n_samples, n_samples_bootstrap)` also requires a 4th `sample_weight` argument on >= 1.9.

**Environment**
- forestci 0.7 (also 0.6 and `master`)
- scikit-learn 1.9.0
- works on scikit-learn <= 1.8

**Suggested fix**

Pass `sample_weight=None` on >= 1.9, guarded by a version check. `None` reproduces the existing uniform-bootstrap behavior (identical `randint` draw), so it is a pure compatibility fix:

```python
from packaging.version import parse as Version
import sklearn

# compare against "1.9.0.dev0" so 1.9 release candidates (which already carry the
# new signatures and sort before the final under PEP 440) are also covered
_SK_GE_19 = Version(sklearn.__version__) >= Version("1.9.0.dev0")
...
if _SK_GE_19:
    n_samples_bootstrap = _get_n_samples_bootstrap(n_samples, forest.max_samples, None)
    idx = _generate_sample_indices(rs, n_samples, n_samples_bootstrap, None)
else:
    n_samples_bootstrap = _get_n_samples_bootstrap(n_samples, forest.max_samples)
    idx = _generate_sample_indices(rs, n_samples, n_samples_bootstrap)
```

Found while adding scikit-learn 1.9 support downstream in [uber/causalml](https://github.com/uber/causalml) (uber/causalml#906). Happy to send a PR if that's welcome.
